### ISSUE TITLE
Error when shutting down homebridge

### ISSUE THREAD

**Issue by Mr-S-D** [snowdd1/homebridge-knx#116]
Hi I am getting the following error every time I am shutting down Homebridge:

/usr/lib/node_modules/homebridge/lib/server.js:528
    this._publishedCameras[advertiseAddress]._associatedHAPAccessory.unpublish();
                          ^

TypeError: Cannot read property '70:30:FA:DD:EB:A5' of undefined
    at /usr/lib/node_modules/homebridge/lib/server.js:528:27
    at Array.forEach (<anonymous>)
    at Server._teardown (/usr/lib/node_modules/homebridge/lib/server.js:527:39)
    at process.<anonymous> (/usr/lib/node_modules/homebridge/lib/cli.js:33:14)
    at emitNone (events.js:106:13)
    at process.emit (events.js:208:7)
    at Signal.wrap.onsignal (internal/process.js:208:44)

Anyone?

**Comment by snowdd1** [comment]
`this._published`**Cameras**`[advertiseAddress]._associatedHAPAccessory.unpublish();`  

Has something to do with the **cameras**, not with KNX.  
Closing that.
