### ISSUE TITLE
Error: EACCES

### ISSUE THREAD

**Issue by marcocastellano** [snowdd1/homebridge-knx#130]
Good morning everyone

When i launch homebridge i receive this strange error
How can I fix it?
Thanx in advance

"Error: EACCES: permission denied, open '/home/pi/.homebridge/knx_config.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Function.User.storeConfig (/usr/local/lib/node_modules/homebridge-knx/lib/user.js:91:6)
    at KNXPlatform.configure (/usr/local/lib/node_modules/homebridge-knx/index.js:231:11)
    at KNXPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-knx/index.js:90:9)
    at emitNone (events.js:106:13)
    at API.emit (events.js:208:7)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:99:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22) "

**Comment by marcocastellano** [comment]
This is the last part when i write home bridge in terminal:

INFO registerSingleGA 1/1/22
[2018-10-28 14:05:17] [homebridge-knx.KNX] Adding service to  accessory Ingresso for: Luce Ingresso
[2018-10-28 14:05:17] [homebridge-knx.KNX] registering new Accessory Ingresso with homebridge
[2018-10-28 14:05:17] [homebridge-knx.KNX] Done with [Ingresso] accessory
[2018-10-28 14:05:17] [homebridge-knx.KNX] We have read 13 devices from file.
[2018-10-28 14:05:17] [homebridge-knx.KNX] Saving config file!
ERROR: There was a problem writing your /home/pi/.homebridge/knx_config.json file.

/usr/local/lib/node_modules/homebridge-knx/lib/user.js:95
		throw err;
		^

Error: EACCES: permission denied, open '/home/pi/.homebridge/knx_config.json'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at Function.User.storeConfig (/usr/local/lib/node_modules/homebridge-knx/lib/user.js:91:6)
    at KNXPlatform.configure (/usr/local/lib/node_modules/homebridge-knx/index.js:231:11)
    at KNXPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-knx/index.js:90:9)
    at API.emit (events.js:185:15)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:99:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:649:30)

**Comment by cgalliani** [comment]
Hi Marco.
I would try adding read and write permission to your knx_config.json by:
$ sudo chmod 666 knx_config.json

**Comment by marcocastellano** [comment]
Thank you, it works!
