### ISSUE TITLE
Cannot find module...

### ISSUE THREAD

**Issue by lonpr** [snowdd1/homebridge-knx#148]
Hey. I wanted to use some handlers in my project. I tried from the example of GiraJalousieActuator - everything is ok. After I decided to try Aircon and PushBittonSwitch, and then the problem appeared:

>[6/4/2019, 2:54:21 PM] [homebridge-knx.KNX] homebridge event didFinishLaunching
[6/4/2019, 2:54:21 PM] [homebridge-knx.KNX] Configuration starts
 [6/4/2019, 2:54:21 PM] [homebridge-knx.KNX] Reading from config: Device/Accessory 1 of 1
 [6/4/2019, 2:54:21 PM] [homebridge-knx.KNX] Service constructor called
[6/4/2019, 2:54:21 PM] [homebridge-knx.KNX] ServiceType defined
[6/4/2019, 2:54:21 PM] [homebridge-knx.KNX] ServiceType known as function
[6/4/2019, 2:54:21 PM] [homebridge-knx.KNX] Found restored service: Impuls Garage
[6/4/2019, 2:54:21 PM] [homebridge-knx.KNX] customServiceAPI.constructor(service, PushButtonSwitch)
[6/4/2019, 2:54:21 PM] Error: Cannot find module './addins/PushButtonSwitch.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:690:17)
at require (internal/modules/cjs/helpers.js:25:18)
at new customServiceAPI (/usr/lib/node_modules/homebridge-knx/lib/customServiceAPI.js:21:18)
at ServiceKNX.loadServiceData (/usr/lib/node_modules/homebridge-knx/lib/service-knx.js:145:28)
at new ServiceKNX (/usr/lib/node_modules/homebridge-knx/lib/service-knx.js:53:25)
at new KNXDevice (/usr/lib/node_modules/homebridge-knx/lib/knxdevice.js:102:23)
at KNXPlatform.configure (/usr/lib/node_modules/homebridge-knx/index.js:216:23)
at KNXPlatform.<anonymous> (/usr/lib/node_modules/homebridge-knx/index.js:90:9)

Why not find these modules?

**Comment by snowdd1** [comment]
You have specified a "handler" name that doesn't exist, probably you meant to name a service
