### ISSUE TITLE
Homebridge crashs after reboot

### ISSUE THREAD

**Issue by tobihoby** [snowdd1/homebridge-knx#165]
Hi,
I have the following error after updating the homebridge:

Plugin - Configure Accessory: Lampe --> Added to restoredAccessories[]
Error: Cannot update reachability on non-bridged accessory! at Accessory._this.updateReachability (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:259:23) at Platform.updateReachability (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/platform.js:88:37) at KNXPlatform.configureAccessory (/home/hoobs/.hoobs/node_modules/homebridge-knx/index.js:163:12) at Server.configCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:332:26) at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:95:14) at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12) at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81) at Module._compile (internal/modules/cjs/loader.js:959:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10) at Module.load (internal/modules/cjs/loader.js:815:32) at Function.Module._load (internal/modules/cjs/loader.js:727:14) at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) at internal/main/run_main_module.js:17:11

then when I manually open the file:
/home/hoobs/.hoobs/etc/accessories/cachedAccessories
delete and reboots, the bridge runs!
Until the next reboot, then the upper error again ...
Delete cachedAccessories -> Reboot = runs again
etc

Problem only with Hoobs version: 3.2.1 !!!

Greets 
Tobihoby

**Comment by tobihoby** [comment]
Problem with hoobs 3.2.1. Fixed in version 3.2.3
