### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'knxd')

### ISSUE THREAD

**Issue by gjniewenhuijse** [snowdd1/homebridge-knx#211]
After updating to the lastest version 0.4.3 i received an error in the log and homebridge doesn't start.

Anyone an idea how to solve?

[26/09/2023, 07:37:39] Registering platform 'homebridge-knx.KNX'
[26/09/2023, 07:37:39] ---
[26/09/2023, 07:37:39] Loading 2 platforms...
[26/09/2023, 07:37:39] [KNX] Initializing KNX platform...
platformconfig=
{ name: 'KNX', platform: 'KNX' }
platformconfig=
{ name: 'KNX', platform: 'KNX' }
---
[26/09/2023, 07:37:40] Got SIGTERM, shutting down Homebridge...
[26/09/2023, 07:37:40] TypeError: Cannot read properties of undefined (reading 'knxd')
    at new KNXPlatform (/usr/local/lib/node_modules/homebridge-knx/index.js:72:30)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:474:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:401:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:176:29)
[26/09/2023, 07:37:42] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/usr/local/lib/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:517:28)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[26/09/2023, 07:37:45] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[26/09/2023, 07:37:50] [HB Supervisor] Restarting Homebridge...
[26/09/2023, 07:37:50] [HB Supervisor] Starting Homebridge with extra flags: -I
[26/09/2023, 07:37:50] [HB Supervisor] Started Homebridge v1.6.1 with PID: 26924

**Comment by gjniewenhuijse** [comment]
problem solved: missing config_path
