### ISSUE TITLE
Deleted Property "MinValue" still throws errors after deleting/updating JSON-file.

### ISSUE THREAD

**Issue by kosmonowt** [snowdd1/homebridge-knx#212]
Hi there, 

I tried your great plugin with my KNX System at home.
While experimenting with the `MinValue` / `MaxValue` I found out that some values were out of bounds and lead to problems in execution. However, after changing or deleting those values from the JSON-file I still have that error, no matter what I do.
Can you help, how to update the `knx_config.json` so the new configuration is taken over?

```
[30.12.2023, 00:41:00] [homebridge-knx] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.
[30.12.2023, 00:41:00] [homebridge-knx] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at CurrentTemperature.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at CurrentTemperature.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2453:21)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:165:16)
    at CurrentTemperature.Characteristic.handleGetRequest (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:736:24)
    at Bridge.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1659:27)
```

**Comment by kosmonowt** [comment]
ok. apparently this was a problem with caching in homebridge itself.
