### ISSUE TITLE
parser error with Version 0.3.10 during start

### ISSUE THREAD

**Issue by hebe2k** [snowdd1/homebridge-knx#89]
Hi @snowdd1,

at each start of homebridge-knx I get the following in the homebridge log:

```
Loading custom types: Got an parser error:  SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-knx/lib/customtypes/knxthermostat.js:52:29)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Don't care, continue...
```

Apart from that Homebridge is running fine.

Regards,
Henning

**Comment by snowdd1** [comment]
That's currently "normal behavior ". The exception got caught, so it can continue to work. Need to fix the root cause though, or remove the functionality altogether, haven't decided yet.
